apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: my-service
spec:
  type: NodePort
  ports:
  - nodePort: 32001 # порт, выставляемый наружу(можно постучаться Postman)
    port: 80
    targetPort: 8080 # внутренний порт пода, совпадает с containerPort
    protocol: TCP
    name: http
  selector:
    app: my-service
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-service
  template:
    metadata:
      labels:
        app: my-service
    spec:
      containers:
      - name: increase-rate-service
        image: nexus.isb/repository/docker-group/my-service # образ docker-контейнера в Nexus
        ports:
        - containerPort: 8080 # порт приложения(указывается в application.yml, по-умолчанию 8080)
        envFrom:
        - configMapRef:
            name: my-service
        env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-service
              key: my_service_password # название секрета, задается коммандой kubectl create secret ...

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: my-service
  labels:
    app: my-service
data: # параметы = application.yml
  POSTGRES_HOST: "127.0.0.1"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "ca"
  # если нужно, можно указать ссылку для другого сервиса в виде OTHER_SERVICE: http://my-other-service:80/api/v1/hello

---
